# now we use the offical paython image as aparent for this docker container
FROM python:3.11

# now we have to lable who is workig on this file 

LABLE maintainer="Muazam Mughal"

# now we have to set the working dir in which the code will run in container

WORKDIR /code

#now we have to install the requied potential python  packages for this contianer

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*


# now we have to install poetry
RUN pip install poetry

# now we have to copy curent directory to the container
COPY ./code/

# configeration to skip virtual env inside the container
RUN poetry config virtualenvs.create false

#install the dependencies
RUN poetry install

# now we have to expose the port on which the app will run
EXPOSE 8000

# Run the application CMD ca be overidden when satrting the container
CMD ["poetry" ,"run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]